name: Build

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '15,45 0,1 * * *'
    - cron: '30 3,9,15,21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./theory.db
            ./theory.db-journal
            ./planet.db
            ./planet.db-journal
          key: ${{ runner.os }}-${{ hashFiles('./theory.ini') }}
      - name: Build
        run: |
          make build
          ls -al
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: theory.report